services:
  mysql:
    image: mysql:8.0
    container_name: mysql_container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: social_app
      MYSQL_USER: user_name
      MYSQL_PASSWORD: user_password
      TZ: Asia/Kolkata
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    deploy:
      resources:
        limits:
          cpus: "0.75"           # Limit to 0.75 CPU cores
          memory: "1.5g"          # Limit to 1.5GB of RAM
        reservations:
          cpus: "0.5"             # Reserve 0.5 CPU cores
          memory: "1g"

volumes:
  mysql_data: